CREATE TABLE `app_ecnomic_t` (
	`title` VARCHAR(50) NULL DEFAULT NULL,
	`detail` VARCHAR(300) NULL DEFAULT NULL,
	`income` DOUBLE NULL DEFAULT NULL,
	`output` DOUBLE NULL DEFAULT NULL,
	`event_date` DATETIME NULL DEFAULT NULL
)